class_name VNDialogueResource
extends Resource

## Compiled dialogue resource.
## Generated by VNScriptCompiler from .dialogue text files.
## Contains a fully resolved array of VNCommand objects ready for execution.

@export var dialogue_id: String = ""
@export var background: Texture2D = null
@export var bgm: AudioStream = null
@export var commands: Array[VNCommand] = []
@export var on_start_events: Array[Dictionary] = []
@export var on_end_events: Array[Dictionary] = []